//***********Form and Forms Validation************** */

console.log("Form and Form Validation")

let nm = document.querySelector("#name")
let form = document.querySelector("#form")
form.addEventListener("submit",(e)=>{
    e.preventDefault()

//    if(nm.value.length <= 2){
//        document.querySelector("#hide").style.display = "block"
//     } else{
//         document.querySelector("#hide").style.display = "none"
//     }

    const regex = /^[a-zA-Z0-9_]{3,20}$/ // we can generate or get regex cutsom code from gpt or internet///dont have need to learn regex
    if(!regex.test(nm.value)){
        document.querySelector("#hide").style.display = "block"
    } else{
        document.querySelector("#hide").style.display = "none"
    }
    console.log(regex.test(nm.value));
})

//Practice of Forms and Validations

let email = document.querySelector("#email")
let password = document.querySelector("#password")
let form2 = document.querySelector("#loginForm")

 let emailError = document.querySelector("#emailError")
    let passwordError = document.querySelector("#passwordError")
    let resultMessage = document.querySelector("#resultMessage")

form2.addEventListener("submit",(e)=>{
    e.preventDefault()
       emailError.textContent = ""
    passwordError.textContent = ""
    resultMessage.textContent = ""
    //regex generated by copilot
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/    
   
    let valid = true
 
    if(!emailRegex.test(email.value)){
        emailError.textContent = "Invalid email format"
        valid = false
    }
    if(!passwordRegex.test(password.value)){
        passwordError.textContent = "Invalid password format"
        valid = false
    }
    
    if(valid){
        resultMessage.textContent = "Form submitted successfully!"
        resultMessage.style.color = "green"
    } else {
        resultMessage.textContent = "Please fix the errors above."
        resultMessage.style.color = "red"
    }
})