const typingParagraphs = [
  `On a bright summer morning the air feels light and fresh. The streets are busy with people walking to work, while children carry their school bags and laugh with their friends. A baker opens his shop and the smell of fresh bread spreads across the road. A man buys a newspaper and sits at a small table outside a cafe, sipping hot coffee while reading the daily news. Birds fly low, looking for crumbs, and a dog waits patiently near his owner. The sky turns a soft blue and the sunlight reflects on windows of tall buildings, making the city look alive. Cars move slowly at the traffic signal, while cyclists ring their bells to pass through. The day begins with small but important actions that together make the town full of life and energy. It is in these simple moments that people find comfort and a sense of belonging, knowing that each morning brings another chance to live, to learn, and to share joy with others. The calmness of the morning slowly turns into the rush of the day, but for a short while, the peace of dawn reminds everyone of the beauty hidden in daily life.`,

  `The ocean has always been a place of wonder and mystery. Standing on the shore, one can hear the waves crash gently against the rocks, leaving behind a trail of foam that sparkles in the sunlight. Children play near the water, building sandcastles that rise tall before the tide washes them away. Far out, a boat sails slowly, moving with the rhythm of the sea. Seagulls circle above, calling out loudly as they search for food. The salty air fills the lungs and the cool breeze touches the skin, bringing a sense of calm to all who stand there. For centuries, sailors have crossed the ocean, chasing dreams and discovering lands. The water carries stories of adventure, loss, and courage, keeping secrets deep within its endless waves. Even today, people come to the beach not only for fun but also to think, to dream, and to feel a part of something greater. The vast blue horizon stretches far and wide, reminding us that the world is huge and full of places yet to be explored. Each wave that touches the sand tells us to keep moving forward, just like the sea never stops its journey.`,

  `Books are powerful companions that shape the way people think and feel. From a young age, reading introduces us to magical worlds where anything is possible. A child opening a book for the first time might find stories of brave heroes, clever animals, or faraway lands. As we grow older, books teach us lessons about history, science, and human nature. They allow us to walk in the shoes of others, to understand their joys and struggles, and to see life from different views. In a quiet library, surrounded by shelves filled with stories, one can travel across centuries without leaving the chair. Some books inspire us to dream big, while others comfort us during hard times. A novel may bring tears, while a poem may bring hope. Unlike movies or games, reading allows the mind to create its own pictures, building worlds with imagination alone. Books are timeless treasures, passed from one generation to another, carrying wisdom and stories that never fade. Every page holds an adventure, every chapter a new chance to learn, and every ending leaves a mark on the heart. That is why books remain among the most important gifts of human knowledge and creativity.`,

  `Technology has changed the way people live, work, and connect with each other. In the past, communication was slow, letters took weeks to arrive, and information traveled at a limited pace. Today, with just one device in hand, anyone can reach friends across the world within seconds. Social media allows us to share pictures, thoughts, and experiences instantly, while video calls bring faces close even from thousands of miles away. Work has also transformed as many jobs can now be done from home, giving people flexibility and saving time. Online education opens doors for students everywhere, no matter where they live. But technology also brings challenges. People sometimes become too dependent on screens, spending less time outdoors or with family. Information overload can also create stress. Still, when used wisely, technology is a powerful tool that connects the world and makes life easier. It allows doctors to perform complex operations, scientists to share research, and businesses to reach global markets. The balance lies in using technology to improve life without letting it control us. In the end, it is not the machine but the person behind it who decides how technology shapes the future.`,

  `Nature has always been the greatest teacher and healer. Walking through a forest, one can feel the calmness that trees spread as they stand tall and quiet. The sound of rustling leaves, the chirping of birds, and the soft flow of a stream all create a peaceful rhythm that clears the mind. Mountains rise high with pride, covered in snow that shines under the sun, while rivers cut their way through valleys, giving life to everything around. Nature teaches patience through the slow growth of trees and strength through the survival of animals in harsh weather. It also teaches balance, reminding us that every creature, no matter how small, has a role in keeping the earth alive. Spending time in nature refreshes the spirit, reduces stress, and makes us appreciate the simple beauty of life. Yet, many forests are cut, rivers polluted, and animals endangered by human actions. Protecting nature is not just about saving plants and animals but also about saving ourselves. A healthy planet ensures a healthy life for all. That is why learning from nature and caring for it is one of the most important responsibilities we share as human beings.`,

  `Friendship is one of the most valuable parts of life. A true friend is not just someone who laughs with you in happy times but also someone who stands by you when things get tough. Friends share secrets, dreams, and fears without judgment. They listen when you need to talk and give advice when you feel lost. Friendship grows stronger through trust and honesty, and even small acts of care can keep it alive. Sometimes friends argue or drift apart, but real friendship always finds a way back. Unlike family, which we are born into, friends are chosen by the heart, making the bond even more special. A walk with a friend can make a long road feel short, and a simple chat can turn a bad day into a good one. Friendships also teach us lessons about loyalty, forgiveness, and understanding. As life changes and people move to different places, friendships may take new shapes, but the memories stay forever. That is why true friends are often called treasures, for they make life richer, brighter, and easier to live.`,

  `Traveling is more than just moving from one place to another; it is a journey of learning and discovery. Visiting a new city allows us to experience different cultures, foods, and traditions. Walking through streets filled with local markets, one can see the colors, hear the voices, and taste the flavors that make each place unique. Meeting people from other parts of the world teaches tolerance and respect, as we realize that even though languages and customs may differ, the emotions of kindness, joy, and hope remain the same everywhere. Traveling also teaches us flexibility, as plans may change, weather may surprise us, and not everything always goes smoothly. But those unexpected moments often create the best memories. A trip to the mountains may bring breathtaking views, while a visit to the sea may bring peace to the heart. Some travel to escape daily stress, while others travel to find inspiration or adventure. No matter the reason, each journey adds stories to our life, reminding us that the world is wide and full of wonders waiting to be explored.`,

  `Time is one of the most mysterious and valuable things in life. It never stops, never slows down, and once it passes, it never comes back. People often say time is money, but in truth, time is much more precious. Money lost can be earned again, but time lost is gone forever. That is why learning to value time is important. A person who uses time wisely can achieve great success, while those who waste it often regret later. Simple habits like waking up early, making plans, and focusing on goals help in saving time. Still, it is not only about working; it is also about living fully. Spending time with family, enjoying hobbies, and resting are just as important as studying or working. Time teaches us patience because not everything happens at once, and it teaches us gratitude because each day is a gift. Looking back, people often remember not the things they bought but the moments they spent. In the end, managing time is not about controlling the clock but about choosing how to live each moment meaningfully.`,

  `School life is a chapter that stays in memory forever. From the very first day, with nervous smiles and new books, to the last farewell filled with tears and laughter, school builds the foundation of who we become. Teachers not only teach lessons from books but also values of discipline, honesty, and kindness. Friends made in school often become friends for life. The sound of the morning bell, the rush to complete homework, and the joy of games on the playground create moments that cannot be replaced. Even the strict teachers, who seemed hard at the time, later become figures we respect deeply. School also brings challenges, such as exams and competitions, but each of these helps us grow stronger and more confident. Years later, when people look back, they realize how those classrooms, corridors, and playgrounds shaped their lives. School is not only about learning facts but also about learning life itself, making it one of the most beautiful and important stages of life.`,

  `Family is the first circle of love and support that every person experiences. Parents give care and guidance, while siblings bring joy and sometimes mischief. Grandparents share stories that carry wisdom from the past, reminding us of values that never fade. Family is where one learns the meaning of sharing, forgiveness, and unconditional love. Even though families are not perfect and disagreements happen, the bond of blood and heart keeps them together. Celebrations feel brighter when shared with family, and hardships feel lighter when faced with their support. A meal at the table becomes more than just food; it becomes a time of connection and warmth. Family also teaches responsibility, as each member has a role to play in keeping harmony. In today’s busy world, where everyone is often running after work or studies, spending time with family is more important than ever. At the end of the day, when the world feels too heavy, family is the place where one finds comfort, safety, and love without conditions.`,

  `Music has a unique power to touch the soul in ways that words often cannot. A soft melody can calm the mind, while a fast beat can fill the body with energy. Music exists in every culture and has been part of human life since ancient times, used in rituals, celebrations, and storytelling. A song can carry memories, reminding us of a moment, a person, or a feeling. Sometimes, a single tune can bring tears, while at other times, it can bring joy so strong that we cannot help but dance. Musicians express their emotions through instruments and voices, creating a bridge between their heart and the listener’s. Music also unites people, as concerts and festivals bring strangers together to share the same rhythm. For students, listening to music while studying can improve focus, while for workers it can make long hours feel lighter. Whether it is classical, rock, jazz, or folk, music continues to heal, inspire, and connect people across the world.`,

  `Hard work has always been the key to success. Talent and luck may help, but without effort, dreams rarely turn into reality. A farmer who wakes early and spends long hours in the field earns a harvest through his labor. A student who studies with focus and discipline achieves good results. Even great athletes and artists spend countless hours practicing before reaching excellence. Hard work builds not only skills but also character. It teaches patience, perseverance, and the ability to keep going even when things get difficult. There are no shortcuts in life that last long; only the path of effort brings results that stay. People sometimes give up when success takes time, but those who continue to push forward eventually achieve their goals. History is full of examples of ordinary people who achieved extraordinary things simply because they worked harder and longer than others. That is why hard work is often called the true secret of success.`,

  `Dreams are the seeds of the future. Every invention, discovery, or achievement began as a dream in someone’s mind. A child may dream of flying, and years later, that dream may lead to building airplanes. Dreams push people beyond limits, inspiring them to imagine what seems impossible. But dreams alone are not enough; they need effort, courage, and belief to turn into reality. Some dreams are small, like learning a skill, while others are big, like changing the world. What matters most is not the size but the passion behind them. Many people fear dreaming big because they worry about failure, but even failures teach lessons and bring us closer to success. Dreams give direction to life, turning ordinary days into a purposeful journey. They keep hope alive during struggles and give energy to move forward. In the end, those who dare to dream and work for it are the ones who shape the future.`,

  `Kindness is a language that needs no words. A simple smile, a helping hand, or a gentle word can change someone’s day. Unlike wealth or power, kindness does not cost anything, yet it brings great rewards. People often remember not what was said but how they were made to feel, and kindness always leaves a lasting mark. It creates trust, builds friendships, and spreads positivity. In times of difficulty, a small act of kindness can bring hope, showing someone that they are not alone. Even in a world filled with challenges and competition, kindness remains a strength, not a weakness. It is not limited to big acts; even opening a door for someone or sharing food is an act of kindness. The more it is practiced, the more it grows, creating a chain reaction that can touch many lives. At its heart, kindness is the purest expression of humanity, reminding us that we are all connected and that compassion is what makes the world a better place.`
];
